sudo: false
dist: trusty
language: python

python:
  - "3.6"

ache:
  pip: true
  apt: true
  directories:
    - $HOME/.cache/pip
    - $HOME/.local

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-6
      - gfortran-6
      - liblapack-dev

git:
  depth: 1
env:
  global:
    - MAKEFLAGS="-j 2"

before_script:
  

script:
  - export BRANCH=$(if [ "$TRAVIS_PULL_REQUEST" == "false" ]; then echo $TRAVIS_BRANCH; else echo $TRAVIS_PULL_REQUEST_BRANCH; fi)
  - echo "TRAVIS_BRANCH=$TRAVIS_BRANCH, PR=$PR, BRANCH=$BRANCH"
  - cd src
  - rm -r -f ../bin/linux/
  - make clean
  - COMPILER=gcc6 CXX=g++-6 FC=gfortran-6 STATIC=no make install
  - cd ..
  - wget http://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - conda update --yes conda
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - conda install --yes python=$TRAVIS_PYTHON_VERSION pip numpy scipy pandas matplotlib nose
  - git clone --depth 1 --single-branch -b develop https://github.com/modflowpy/flopy.git
  - cd flopy
  - python setup.py install
  - cd ..
  - git clone --depth 1 --single-branch -b develop https://github.com/jtwhite79/pyemu.git
  - cd pyemu
  - python setup.py install
  - cd ..
  - export PYTHONPATH=$PYTHONPATH:.
  - export PATH="./test_bin/linux:../test_bin/linux:../../test_bin/linux:$PATH"
  - nosetests -v -w ./benchmarks ci_prep.py
  - #nosetests -v -w ./benchmarks ies_test.py


after_success:
  - chmod +x trigger-travis.sh
  - ./trigger-travis.sh --branch $BRANCH jtwhite79 pestpp-opt_benchmarks $TRAVIS_ACCESS_TOKEN
  - ./trigger-travis.sh --branch $BRANCH jtwhite79 pestpp-ies_benchmarks $TRAVIS_ACCESS_TOKEN
  - ./trigger-travis.sh --branch $BRANCH jtwhite79 pestpp-ies_benchmarks2 $TRAVIS_ACCESS_TOKEN
  - ./trigger-travis.sh --branch $BRANCH jtwhite79 pestpp-ies_benchmarks_base $TRAVIS_ACCESS_TOKEN
notifications:
  email: true
